### ISSUE TITLE
SocketComms data can fall behind and never catch up

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1285]
the current way socketComms is currently designed is that the queue will acculmulate indefinitely. The consumer always runs at least at the same rate or lower.  If the main thread is backed up, it will progressively fall behind and never recover. 

We need to limit how much data is queued so data is dropped if needed to keep the UI responsive.

**Comment by stieg** [comment]
Would it instead just be wiser to drain the queue on every iteration of the refresh instead of taking a single sample.  This way everything gets processed but only the latest update shows up on the UI.

**Comment by brentpicasso** [comment]
possibly. the main reason for this falling behind is due to slower devices, so we will have to drop data at some point.

**Comment by stieg** [comment]
> the main reason for this falling behind is due to slower devices

The device producing this data has trivial resources relative to even the oldest ones supported (Old galaxy tabs or Kindle fire 7") that receive and process this data and you are telling me that these more powerful devices can't keep up?  From where I sit this would indicate a larger design issue as the culprit rather than the devices themselves.
