### ISSUE TITLE
resizing the window under linux generares CRITICAL messages.

### ISSUE THREAD

**Issue by RodADavison** [autosportlabs/RaceCapture_App#1492]
[CRITICAL] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute

I was view the "Dashboard" screen that shows all the channels as numbers, at the time.  It only seems to happen when resizing vertically.

**Comment by brentpicasso** [comment]
This is a warning from Kivy complaining about the amount of time needed to render - it's otherwise harmless to the app. 

It's only a problem if it keeps happening every frame. See the comments on this post:
https://stackoverflow.com/questions/37248450/why-am-i-getting-warning-too-much-iteration-done-before-the-next-frame

**Comment by RodADavison** [comment]
The symptoms are definitely benign, but I'd like to see the production version of the app run without generating CRITICAL messages.  $0.02.
