### ISSUE TITLE
Incompatible mobile app + firmware issue

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#867]
Just discovered a situation that may break app functionality for users:

1) User installs latest mobile app & firmware
2) We push out a new MAJOR app & firmware version and the user's phone/tablet is auto-updated over wifi/cellular. This major version breaks compatibility with the previous firmware version. The user does not update their firmware.
3) User goes to the track/race/etc, now their phone or tablet can't talk to RCP because it has new or changed functionality and can't talk to older versions of RC firmware.

Users don't generally bring USB cables and have a laptop and internet at a track, so they can't update the firmware. There's no simple/easy way to downgrade their app. So then they are SOL. 

Possible fixes are:

1) Bundle latest firmware with app, add BT firmware flashing to app and firmware
2) Make the app always be able to talk to at least N previous firmware versions
3) Add in some sort of API version negotiation between app & firmware, allowing the app to appropriately send data to the firmware that it will understand.

**Comment by stieg** [comment]
IIRC the plan for this situation was option 3.  We needed this because:

* Not all versions APIs will be available to all users (think MK1 vs MK2 in example)
* We need to be able to easily test out new commands and fall back if things break for some unexpected reason.
* Its unreasonable for us to expect users to update more than one thing at a time.  This is inline with the above scenario.

**Comment by brentpicasso** [comment]
Option 3 seems to be the option we're doing with the capabilities flags. Closing.
